### ISSUE TITLE
Warning: sciensano_style, please spesify a font

### ISSUE THREAD

**Issue by raphalj** [sciensanogit/ggsano#1]
Hi,
Many thanks for the ggsano package.
I get a "please specify an available font" when I run the sciensano_style function.
Does someone know how to avoid getting this warning?

Here is my code:
```
> final_plot <- finalise_plot(
+   plot_name = p1 + 
+     sciensano_style(font = "Arial") +
+     ggtitle("Evolution des charges virales", subtitle = ) +
+     theme(legend.key.width = ggplot2::unit(2.5, "cm")),
+   source_name = "Source: mtcars",
+   save_filepath = FALSE,
+   width_pixels = 640,
+   height_pixels = 450,
+   logo_image_path = file.path(system.file("extdata", package = "ggsano"), "logo.png")
+ )
```
I get the following warning:
```
Using font: 
Warning message:
In sciensano_style(font = "Arial") : Please specify an available font
The first available font will be taken:
```

Many thanks for your help,
ps: this is my first issue report, so let me know if I did something wrong.
Best regards,

**Comment by rdpauw** [comment]
Hi, you could specify a Font that is available in R on your computer. You could check this by running: extrafont::fonts().
