### ISSUE TITLE
Impossible to add a ylabel with the finalise_plot function

### ISSUE THREAD

**Issue by raphalj** [sciensanogit/ggsano#2]
Hi everyone,
It would be nice to add the following feature to the finalise_plot function: the possibility to add a ylabel to the graph.
This would be particularly useful when the units of the graph must be displayed.
Best day to all

**Comment by eliasvermeiren** [comment]
This can be bypassed by adding a theme(axis.title = element_text(size=20)) (size can be anything you want) after the sciensano_style() function in your plot object.

eg.

ggplot()+
    geom_point(data=df, aes(x=variable, y=value))+
    sciensano_style()+
    theme(axis.title = element_text(size=20))+
    ylab("y-axis title")

________________________________
Van: raphalj ***@***.***>
Verzonden: donderdag 13 oktober 2022 14:14
Aan: sciensanogit/ggsano ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [sciensanogit/ggsano] Impossible to add a ylabel with the finalise_plot function (Issue #2)


Hi everyone,
It would be nice to add the following feature to the finalise_plot function: the possibility to add a ylabel to the graph.
This would be particularly useful when the units of the graph must be displayed.
Best day to all

**Comment by raphalj** [comment]
This works fine. Many thanks.
